name: Make, Create and Upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: "0 12 * * *"

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'liberica'
          architecture: 'x64'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make
        run: make
      - name: Create XML Sitemap
        run: mkdir -p run && java -jar ./build/btsm.jar | tee run/latest.log
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          sh -c "git branch -D hidden | cat"
          git checkout --orphan hidden
          cp ./run/*.xml ./run/latest.log .
          git add *.xml latest.log
          git commit *sitemap.xml latest.log -m "feat: sitemap"
          git remote set-url origin https://user:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin hidden -f
